#!/usr/bin/env bash
#
# Build bagfile_parser_qt from source and install it on this machine
# (Linux or macOS).
#
# Most people should instead grab a prebuilt .deb / .dmg / installer, or build
# one with scripts/package.sh. Use this when you want the binary installed
# straight into a prefix on the machine you're sitting at.
#
#   ./scripts/install.sh                   # install into /usr/local
#   ./scripts/install.sh --prefix ~/.local
#   ./scripts/install.sh --no-deps
#   ./scripts/install.sh --uninstall
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/common.sh
. "${REPO_ROOT}/scripts/common.sh"

BUILD_DIR="${REPO_ROOT}/build"
PREFIX=""
BUILD_TYPE="Release"
JOBS=""
INSTALL_DEPS=1
DO_UNINSTALL=0

usage() {
    sed -n '2,15p' "${BASH_SOURCE[0]}" | sed 's/^#\s\?//'
    cat <<EOF

Options:
  --prefix DIR        Install prefix (default: /usr/local, or ~/.local when
                      /usr/local is not writable and sudo is unavailable)
  --build-type TYPE   CMake build type (default: Release)
  -j, --jobs N        Parallel compile jobs (default: all cores)
  --no-deps           Do not install system packages
  --uninstall         Remove a previous install, then exit
  -h, --help          Show this help
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)     PREFIX="${2:?--prefix needs a directory}"; shift 2 ;;
        --prefix=*)   PREFIX="${1#*=}"; shift ;;
        --build-type) BUILD_TYPE="${2:?--build-type needs a value}"; shift 2 ;;
        -j|--jobs)    JOBS="${2:?--jobs needs a number}"; shift 2 ;;
        --no-deps)    INSTALL_DEPS=0; shift ;;
        --uninstall)  DO_UNINSTALL=1; shift ;;
        -h|--help)    usage; exit 0 ;;
        *)            die "unknown option: $1 (try --help)" ;;
    esac
done

detect_os
[ -n "$JOBS" ] || JOBS="$(default_jobs)"

# Pick a prefix, then decide whether writing to it needs sudo.
if [ -z "$PREFIX" ]; then
    if need_sudo_for /usr/local && ! command -v sudo >/dev/null 2>&1; then
        PREFIX="$HOME/.local"
        info "no sudo available; defaulting to --prefix $PREFIX"
    else
        PREFIX="/usr/local"
    fi
fi
case "$PREFIX" in "~"/*) PREFIX="$HOME/${PREFIX#\~/}" ;; esac

SUDO=""
if need_sudo_for "$PREFIX"; then
    command -v sudo >/dev/null 2>&1 || die "$PREFIX is not writable and sudo is not available"
    SUDO="sudo"
fi

# ------------------------------------------------------------- uninstall ----
if [ $DO_UNINSTALL -eq 1 ]; then
    MANIFEST="${BUILD_DIR}/install_manifest.txt"
    [ -f "$MANIFEST" ] || die "no install manifest at $MANIFEST; nothing to uninstall from this tree"
    step "Removing files listed in $MANIFEST"
    # `|| [ -n "$f" ]` so the final line is handled even without a trailing
    # newline, which is how CMake writes install_manifest.txt.
    while IFS= read -r f || [ -n "$f" ]; do
        [ -n "$f" ] || continue
        if [ -e "$f" ] || [ -L "$f" ]; then
            $SUDO rm -f "$f" && info "removed $f"
        fi
    done < "$MANIFEST"

    if [ "$OS" = "Darwin" ]; then
        $SUDO rm -rf "$PREFIX/Applications/bagfile_parser_qt.app"
        $SUDO rm -f "/Applications/bagfile_parser_qt.app"
    else
        # Caches regenerated by the post-install step, not in the manifest.
        $SUDO rm -f "$PREFIX/share/applications/mimeinfo.cache" \
                    "$PREFIX/share/icons/hicolor/icon-theme.cache"
    fi
    step "Uninstalled"
    exit 0
fi

# ---------------------------------------------------------- dependencies ----
if [ $INSTALL_DEPS -eq 1 ]; then
    install_deps "$SUDO"
else
    step "Skipping dependency install (--no-deps)"
fi
command -v cmake >/dev/null 2>&1 || die "cmake not found on PATH"

# ----------------------------------------------------------------- build ----
CMAKE_ARGS=(-S "$REPO_ROOT" -B "$BUILD_DIR"
            -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
            -DCMAKE_INSTALL_PREFIX="$PREFIX")

if [ "$OS" = "Darwin" ]; then
    qt_flag="$(macos_qt_prefix_flag)"
    [ -n "$qt_flag" ] && CMAKE_ARGS+=("$qt_flag")
fi
command -v ninja >/dev/null 2>&1 && CMAKE_ARGS+=(-G Ninja)

step "Configuring (prefix: $PREFIX, build type: $BUILD_TYPE)"
cmake "${CMAKE_ARGS[@]}"

step "Building with $JOBS job(s)"
cmake --build "$BUILD_DIR" --parallel "$JOBS"

step "Installing to $PREFIX"
$SUDO cmake --install "$BUILD_DIR"

# ---------------------------------------------------------- post-install ----
if [ "$OS" = "Darwin" ]; then
    APP_SRC="$PREFIX/Applications/bagfile_parser_qt.app"
    if [ -d "$APP_SRC" ] && [ -w /Applications ]; then
        step "Linking the app into /Applications"
        rm -f "/Applications/bagfile_parser_qt.app"
        ln -s "$APP_SRC" "/Applications/bagfile_parser_qt.app"
        info "launch it from Finder, Spotlight or Launchpad"
    elif [ -d "$APP_SRC" ]; then
        info "app bundle installed at $APP_SRC"
        info "link it into /Applications with:"
        info "  sudo ln -sfn '$APP_SRC' /Applications/bagfile_parser_qt.app"
    fi
else
    # Refresh the desktop/icon caches so the launcher appears without a re-login.
    command -v update-desktop-database >/dev/null 2>&1 && \
        $SUDO update-desktop-database "$PREFIX/share/applications" >/dev/null 2>&1 || true
    command -v gtk-update-icon-cache >/dev/null 2>&1 && \
        $SUDO gtk-update-icon-cache -f -t "$PREFIX/share/icons/hicolor" >/dev/null 2>&1 || true
fi

BIN="$PREFIX/bin/bagfile_parser_qt"
step "Installed $BIN"
case ":$PATH:" in
    *":$PREFIX/bin:"*) info "run it with: bagfile_parser_qt --help" ;;
    *)
        warn "$PREFIX/bin is not on your PATH. Add this to your shell profile:"
        info "  export PATH=\"$PREFIX/bin:\$PATH\""
        info "or run it directly: $BIN --help"
        ;;
esac
printf '%sDone.%s\n' "$C_GREEN" "$C_OFF"
